#!/bin/bash
#
#Arnold Milihhin, menu, skript mis väljastab menüüd
#
for((m=1;m<4;m++))
do
cat menu$m
done
echo "sisesta number 1-3"
read number
case $number in
1)echo -e "Stick to your ribs.\n Watch your cholesterol\n Enjoy your meal";;
2)echo -e "british are coming.\n Enjoy your meal";;
3)echo -e "health foods\nDieting is so boring\n Enjoy your meal";;
esac




