#!/bin/bash
#
#Arnold Milihhin, menu, skript mis väljastab menüüd
#
for((m=1;m<4;m++))
do
cat menu$m
done
echo "sisesta number 1-3"
read number
case $number in
1)echo -e "stick to your ribs...........";;
2)echo -e "british are coming...........";;
3)echo -e "health foods.....";;
esac




